--1
SELECT ENAME, JOB, SAL,
CASE
  WHEN SAL < 1000 THEN 'Niska pensja'
  WHEN SAL BETWEEN 1000 AND 2000 THEN 'Średnia pensja'
  WHEN SAL > 2000 THEN 'Wysoka pensja'
  ELSE 'Brak wartości'
END AS SALARY_STATUS
FROM EMP

--2
select ename, sal, nvl(comm, '0') as comm
from emp;

select ename, sal, nvl2(comm, comm, '0') as comm
from emp;

select ename, sal, COALESCE(comm, 0) as comm
from emp;

--3
select * from emp order by comm nulls last;
select * from emp order by comm nulls first;

--4
SELECT UID, USER FROM DUAL

--5
SELECT TO_DATE ('6 April 1997', 'DD MON YYYY') FROM DUAL

--6
SELECT MONTHS_BETWEEN(
    SELECT * FROM (SELECT HIREDATE FROM EMP ORDER BY HIREDATE DESC) WHERE ROWNUM = 1,
    SELECT * FROM (SELECT HIREDATE FROM EMP ORDER BY HIREDATE ASC) WHERE ROWNUM = 1)
    "Months"
FROM DUAL;

--7
SELECT LAST_DAY(SYSDATE) "Last" FROM DUAL;

--8
select to_number(to_char(last_day(TO_DATE('02-2022','mm/yyyy')),'dd')) TotalDays from dual

--9
SELECT ROUND (ADD_MONTHS(TO_DATE(SYSDATE),50), 'YEAR') "Rounded" FROM DUAL;

--10
SELECT TO_CHAR(date '2021-12-31', 'DAY') day FROM dual 

--11
SELECT ADD_MONTHS(SYSDATE, 3) FROM DUAL;

--12
SELECT (SYSDATE + 3) - interval '1' hour FROM DUAL;

--13
SELECT TO_CHAR(ROUND(TRUNC(AVG(SAL),2),2)) FROM EMP

--14
SELECT SAL FROM (SELECT * FROM EMP WHERE JOB='MANAGER' ORDER BY SAL ASC) WHERE ROWNUM=1

--15
SELECT COUNT(*) FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO WHERE DEPT.DNAME='ACCOUNTING'

--18
SELECT DNAME, AVG(SAL) "Średnie zarobki" FROM EMP NATURAL JOIN DEPT GROUP BY DNAME
  
--19
 SELECT JOB, MAX(SAL) FROM EMP GROUP BY JOB HAVING JOB!='CLERK'
 
--20
 SELECT DNAME, JOB, MIN(SAL) FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO GROUP BY DNAME, JOB
 
--21
 SELECT DNAME, AVG(SAL) FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO GROUP BY DNAME
 
--22
 SELECT JOB, AVG(SAL) FROM EMP WHERE SAL >= 2000 GROUP BY JOB
 
--23
 SELECT DNAME, (MAX(SAL) - MIN(SAL)) AS "Różnica" FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO GROUP BY DNAME
 
--24
SELECT ENAME FROM EMP WHERE SAL < (SELECT SAL FROM EMP WHERE JOB = 'MANAGER');

--25
select * from (select * from emp order by sal desc) where rownum <=3

--26
select ename, sal, (select max(sal) from emp) as Salary_max from emp;

--27
SELECT * FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP)

--28
SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME = 'SMITH')

--29
ALTER SESSION SET NLS_SORT = Polish;

--30
SELECT ENAME, DEPTNO, SAL FROM EMP a WHERE SAL = (SELECT MAX(SAL) FROM EMP WHERE EMP.DEPTNO = a.DEPTNO) ORDER BY DEPTNO;

--31 
SELECT * FROM EMP WHERE SAL > ANY (SELECT SAL FROM EMP WHERE DEPTNO = 10)

--32
SELECT * FROM EMP WHERE SAL > ALL (SELECT SAL FROM EMP WHERE DEPTNO = 30)

--33
SELECT JOB FROM EMP GROUP BY JOB HAVING AVG(SAL) > (SELECT AVG(SAL) FROM EMP WHERE JOB = 'MANAGER');

--34
SELECT JOB FROM EMP GROUP BY JOB HAVING AVG(SAL) = (SELECT MIN(AVG(SAL)) FROM EMP GROUP BY JOB);

--35
SELECT ENAME, JOB, SAL FROM EMP WHERE SAL < ALL (SELECT AVG(SAL) FROM EMP GROUP BY JOB);

--36
SELECT ENAME FROM EMP e1 WHERE EXISTS (SELECT NULL FROM EMP e2 WHERE e2.MGR = e1.EMPNO);

--37
SELECT DNAME FROM DEPT d WHERE NOT EXISTS (SELECT 1 FROM EMP e WHERE e.DEPTNO = d.DEPTNO);



 